= Awesome Qt
:icons: font
:toc: macro
:toc-title:

:MIT: http://opensource.org/licenses/MIT[MIT license.]

A curated list of links to awesome Qt-related libraries, tools, and other
resources published under Free Software/Open Source licenses.

Don't forget to check http://doc.qt.io/qt-5/qtmodules.html[the list of essential
and add-on modules from the Qt project] first! Upcoming modules might be in
`qt-labs` or `playground` in http://code.qt.io/[code.qt.io]. And remember that
there is https://github.com/fffaraz/awesome-cpp[Awesome C/C++] for more projects
that don't use Qt.

toc::[]

== Libraries


=== User Interface

https://github.com/mikemcquaid/Qocoa::
Wrappers for OS X Cocoa widgets. {MIT}

https://github.com/cybercatalyst/qtsystemtrayiconmac::
Extended QSystemTrayIcon for Mac OS X.


=== Graphics

https://github.com/gamecreature/QtAwesome::
Library for using http://fortawesome.github.io/Font-Awesome/[Font Awesome] or
other icon sets based on font files.

http://qwt.sourceforge.net/::
Qt Widgets for Technical Applications. Contains GUI Components and utility
classes which are primarily useful for programs with a technical background.
Beside a framework for 2D plots it provides scales, sliders, dials, compasses,
thermometers, wheels and knobs to control or display values, arrays, or ranges
of type double.


=== File formats

https://github.com/flavio/qjson::
Library that maps JSON data to QVariant objects. Supports Qt 4.

https://github.com/gaudecker/qt-json::
A simple class for parsing JSON data into a QVariant hierarchy and vice versa.
Supports Qt 4.


=== Multimedia

http://www.qtav.org/::
QtAV is a multimedia playback library based on Qt and FFmpeg. Supports Android,
iOS and desktops.


=== Inter process communication

=== Threading

=== Network protocols and web services

https://github.com/wiedi/libmaia::
XML-RPC library.

=== Hardware detection and interaction

=== Other programming languages

https://github.com/seanchas116/libqmlbind::
A C library for easily creating QML bindings for other languages by exporting
objects to QML. In use in `ruby-qml`.

http://thp.io/2011/pyotherside/::
Asynchronous Python 3 Bindings for Qt 5. This is a QML Plugin that provides
access to a Python 3 interpreter from QML.

http://seanchas116.github.io/ruby-qml/::
Bindings between Ruby and QML. Enables you to write Qt Quick GUIs in Ruby.

https://github.com/trollixx/node.qml::
a Node.js compatibility layer to QML applications. Potentially, QML applications
should be able to use majority of Node.js libraries.


=== Miscellany

https://github.com/sergey-shambir/breakpad-qt::
Cross-platform crash handler, implemented as wrapper around google-breakpad.

https://github.com/dschmidt/libcrashreporter-qt::
libcrashreporter-qt is supposed to provide an easy integration of Google
Breakpad crash reporting into a Qt application.

https://github.com/Roxee/qt-roxeemegaup/::
Wrapper around Sparkle and WinSparkle.

https://github.com/Roxee/qt-roxeeplatipus::
A collection of helpers and additional functionalities for Qt (media key
support, OS X remote control, fullscreen native window hack).

https://github.com/Roxee/qt-roxeesinapp::
An up to date QtSingleApplication fork.

https://github.com/VerbalExpressions/QtVerbalExpressions::
Regular Expressions made easy. Match and replace in strings with an easy to use
API.


=== Web frameworks

http://cutelyst.org/::
MVC web framework inspired in Perl's Catalyst.

https://github.com/jlaine/qdjango/::
QDjango is a web framework written in C++ and built on top of the Qt library.
Where possible it tries to follow django's API, hence its name.

https://github.com/vinipsmaker/tufao::
Tufão is a web framework for C++ that makes use of Qt's object communication
system (signals & slots).


=== Event loop dispatchers

https://github.com/sjinks/qt_eventdispatcher_epoll::
epoll-based event dispatcher

https://github.com/connectedtable/qeventdispatcher_epoll::
epoll event dispatcher

https://github.com/sjinks/qt_eventdispatcher_libevent::
libevent-based event dispatcher

https://github.com/sjinks/qt_eventdispatcher_libev::
libev-based event dispatcher

https://github.com/svalaskevicius/qt-event-dispatcher-libuv::
libuv event dispatcher



== Tools

https://github.com/KDAB/GammaRay::
GammaRay is a tool to poke around in a Qt-application and also to manipulate the
application to some extent.

https://github.com/robertknight/Qt-Inspector::
Utility to browse the Qt object tree of a running Qt application and edit object
properties on the fly



== Off topic

NOTE: Stuff that might not integrate at all with Qt's types, API, event loop,
etc., but still an application built with Qt can leverage it well enough because
it is cross platform native code that fulfills a common use case of the typical
Qt applications.

https://github.com/Mendeley/breakpad::
This is a fork of Google Breakpad, a multi-platform crash reporting system,
which is used by Mendeley Desktop under Windows, Mac and Linux.

https://github.com/Mendeley/Update-Installer::
Small cross-platform software update installer.
